# Generated by Django 6.0.3 on 2026-03-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'verbose_name': 'Sugestão', 'verbose_name_plural': 'Sugestões'},
        ),
    ]
