# Generated by Django 6.0.3 on 2026-03-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_suggestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='feedback_agency',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta do Órgão'),
        ),
    ]
