# Generated by Django 6.0.3 on 2026-04-03 12:25

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaints_options_alter_complaints_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='city',
            field=models.CharField(default='Trindade, Goiás', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='complaints',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='-16.6497,-49.4935', max_length=63, verbose_name='Mapa'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
