# Generated by Django 6.0.3 on 2026-07-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_alter_suggestion_options_pushsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplaintsInventory',
        ),
    ]
